#!/bin/bash

PMS_LIB_DIR=/usr/lib/plexmediaserver
PMS_DOWNLOAD_DIR=/tmp/plex_tmp_download
PMS_DOWNLOAD_NAME="plexmediaserver.deb"

VERSION="1.3.3.3148-b38628e"
PMS_URL="https://downloads.plex.tv/plex-media-server/${VERSION}/plexmediaserver-ros6-binaries-annapurna_${VERSION}_armel.deb"
PMS_HASH="ece8e6aa07908255fb49990623d6f2f57973362b"

case "$1" in
    configure)
        adduser --quiet --system --shell /bin/bash --home /var/lib/plexmediaserver plex
        update-rc.d plexmediaserver defaults
        /etc/init.d/plexmediaserver stop

        # create dirs
        mkdir -p "${PMS_DOWNLOAD_DIR}"
        mkdir -p "${PMS_LIB_DIR}"

        cd "${PMS_DOWNLOAD_DIR}"
        curl --progress-bar -o ${PMS_DOWNLOAD_NAME} ${PMS_URL}

        PMS_DOWNLOAD_HASH=$(sha1sum ${PMS_DOWNLOAD_NAME} | cut -d' ' -f1)

        if [ "${PMS_HASH}" != "${PMS_DOWNLOAD_HASH}" ]; then
            echo "Checksum mismatch. Downloaded file does not match this package."
            exit 1
        else
            echo "Passed checksum test."
        fi

        echo "Extracting ${PMS_DOWNLOAD_NAME} ..."
        dpkg-deb --fsys-tarfile ${PMS_DOWNLOAD_NAME} | tar -xf - -C "${PMS_LIB_DIR}/" --strip-components=4 ./apps/plexmediaserver-annapurna/Binaries

        # remove not used files
        rm "${PMS_LIB_DIR}/config.xml"

        # remove tmp data
        cd /tmp
        rm -r "${PMS_DOWNLOAD_DIR}/"

        /etc/init.d/plexmediaserver start
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
